routes/web.php
<?php
use Illuminate\Support\Facades\Route;

//Inicio
Auth::routes();
Route::get('/','IndexController@index');
Route::get('/home', 'HomeController@home')->name('home');

//Listar
Route::get('/posts/{id}','PostController@posts')->name('posts');//Posts por categoria
Route::get('/listpost','PostController@listPost');//Listar tabla vista posts por AJAX
Route::get('/post/{id}','PostController@post')->name('post');//Detalle post, seccion comentarios

//Ruta AJAX insertar, eliminar Post.
Route::resource('post','PostController');
Route::resource('cmt','CommentController');
Route::get('/listcmt','CommentController@listCmt');//Listar comentarios por AJAX

//Insertar
Route::post('/crearcmt', 'CommentController@insertarCmt')->name('crearcmt');
Route::post('/crearcat', 'CategoryController@insertarCat')->name('crearcat');

//Eliminar
//Route::delete('/borrarcmt/{id}', 'CommentController@borrarCmt')->name('borrarcmt');
Route::delete('/borrarcat/{id}', 'CategoryController@borrarCat')->name('borrarcat');

//Editar
Route::put('/editarcat/{id}','CategoryController@editarCat')->name('editarcat');
Route::get('/datospost','PostController@editmostrar')->name('datospost');//Mostrar post seleccionado
Route::put('/editarpost','PostController@edit')->name('editarpost');//Actualizar post seleccionado
Route::get('/datoscmt','CommentController@editmostrar')->name('datoscmt');//Mostrar cmt seleccionado
Route::put('/editarcmt','CommentController@edit')->name('editarcmt');//Actualizar cmt seleccionado
//Route::put('/editarcmt/{id}','CommentController@editarCmt')->name('editarcmt');



//Likes - Post
Route::get('/likepost', 'PostController@addLikePost');

//Likes - Comment
Route::get('/likecmt', 'CommentController@addLikeCmt');

//Añadir post a favoritos
Route::post('addfavorite' , 'PostController@AddFavPost');

//Vista favoritos
Route::get('myfavorites', 'PostController@userFavorites');
Route::get('myposts', 'PostController@userPosts');

resources/views/modal/create-category.blade.php
<!-- Modal insertar -->
<div class="modal fade" id="publicCat" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">

            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Crear categoria</h5>
            <button align="right" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>

            <div class="modal-body">
            <form action="{{ route('crearcat')}}" method="POST">
                @csrf
                <div>
                <label>Nombre</label>
                <div>
                    <input type="text" class="form-control " name="name"  required autocomplete="name" autofocus>
                </div>
                </div>
                <div>
                <label>Descripcion *</label>
                <div>
                    <textarea type="text" class="form-control" name="description"  required autocomplete="description" autofocus></textarea>
                </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Publicar</button>
                </div>
            </form>
            </div> 

        </div>
    </div>
</div>

resources/views/modal/create-post.blade.php
<div class="modal fade modalPublicarPost" id="modalPublicarPost" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Crear publicacion</h5>
        <button align="right" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <form id="addPost" >
          @csrf
          <input type="hidden" value="{{$cat->id}}" name="category_id" id="category_id">
          <div align="left">
            <label>Titulo</label>
            <div>
              <input type="text" class="form-control" name="title" id="title" required autocomplete="title" autofocus>
            </div>
          </div>
          <br>
          <div align="left">
            <label>Contenido *</label>
            <div>
              <textarea type="text" class="form-control" name="content" id="content" required autocomplete="content" autofocus></textarea>
            </div>
          </div>
          <div class="modal-footer"> 
            <button type="submit" class="btn btn-primary" id="btnPost">Publicar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<!-- AJAX Insertar -->
<script>
  $('#btnPost').click(function(event){
    event.preventDefault();
    var token = $("input[name=_token]").val();
    var form = $('#addPost');
    var route = "{{route('post.store')}}";
    $.ajax({
      type: "post",
      headers: {"X-CSRF-TOKEN":token},
      url: route,
      data: form.serialize(),
      dataType: "json",
      success: function (data) 
      {
        if(data.success == 'true' )
        {
          listPost();
          $('#modalPublicarPost').modal('hide');
          $('.modal-backdrop').remove();
        }
      }
    });
  });
</script>

resources/views/modal/delete-category.blade.php
<!-- Modal eliminar -->
<div class="modal fade" id="borrarCat{{$categorias->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
        <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">La categoria se eliminara.</h5>
            <button type="button" class="close" data-dismiss="modal" aria-label="Close">
            <span aria-hidden="true">&times;</span>
            </button>
        </div>
        <form action="{{route('borrarcat', $categorias)}}" method="POST">
            @method('DELETE')
            @csrf                  
            <div class="modal-footer">
            <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
            <button type="submit" class="btn btn-primary">Borrar</button>
            </div>
        </form>
        </div>
    </div>
</div>

resources/views/modal/delete-cmt.blade.php
<div class="modal fade modalborrarcmt" id="borrarCmt{{$comentario->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">El comentario se eliminara.</h5>
                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                </button>
            </div>                
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
                <button class="btn btn-primary deleteCmt"  data-id="{{$comentario->id}}" data-token="{{ csrf_token() }}" >Borrar</button>
            </div>
        </div>
    </div>
</div>
<!-- AJAX Eliminar -->
<script>
  $(".deleteCmt").click(function(){
  var id = $(this).data("id");
  var token = $(this).data("token");
  var route = "{{route('cmt.store')}}";
  $.ajax(
  {
    url: route+"/"+id,
    type: 'DELETE',
    dataType: "JSON",
    data: {"id": id, "_method": 'DELETE', "_token": token,},
    success: function (data)
    {
        listCmt();
        $('.modalborrarcmt').modal('hide');
        $('.modal-backdrop').remove();
    }
  });
});
</script>

resources/views/modal/delete-post.blade.php
<div class="modal fade modalborrar" id="modalBorrarPost" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">La publicacion se eliminara.</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-dismiss="modal">Cancelar</button>
        <button class="btn btn-primary deletePost"  data-id="{{$post->id}}" data-token="{{ csrf_token() }}" >Borrar</button>
      </div>
  </div>
</div>
<!-- AJAX Eliminar -->
<script>
  $(".deletePost").click(function(){
  var id = $(this).data("id");
  var token = $(this).data("token");
  var route = "{{route('post.store')}}";
  $.ajax(
  {
    url: route+"/"+id,
    type: 'DELETE',
    dataType: "JSON",
    data: {"id": id, "_method": 'DELETE', "_token": token,},
    success: function (data)
    {
        listPost();
        $('.modalborrar').modal('hide');
        $('.modal-backdrop').remove();
    }
  });
});
</script>

resources/views/modal/edit-category.blade.php
<!-- Modal editar -->
<div class="modal fade" id="editar{{$categorias->id}}" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
            <h5 class="modal-title" id="exampleModalLongTitle">Editar categoria</h5>
            <button align="right" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
            <form action="{{route('editarcat',$categorias)}}" method="POST">
                @method('PUT')
                @csrf
                <div>
                <div>
                    <input type="text" value="{{$categorias->name}}" class="form-control @error('name') is-invalid @enderror" name="name"  required autocomplete="name" autofocus>
                </div>
                </div>
                <br>
                <div>
                <div>
                    <textarea type="text" class="form-control" name="description"  required autocomplete="description" autofocus>{{$categorias->description}}</textarea>
                </div>
                </div>
                <div class="modal-footer">
                    <button type="submit" class="btn btn-primary">Editar</button>
                </div>
            </form>
            </div>
        </div>
    </div>
</div>

resources/views/modal/edit-cmt.blade.php
<div class="modal fade" id="modalEditarCmt" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
    <div class="modal-dialog modal-dialog-centered" role="document">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="exampleModalLongTitle">Editar comentario</h5>
                <button align="right" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
            </div>
            <div class="modal-body">
                <form id="editCmt">
                <input type="hidden" id ="idcmt" name="cmt">
                @csrf
                <div>
                    <div>
                        <input type="text" class="form-control" name="comment" id="cmtedit"  required autocomplete="comment" autofocus>
                    </div>
                </div>
                <div class="modal-footer">
                    <button id="btnEditCmt" type="submit" class="btn btn-primary">Editar</button>
                </div>
                </form>
            </div>
        </div>
    </div>
</div>
<script>
    $('button[id=openmodalcmt]').on('click',function () {
      var id = $(this).data("id");
      $('#idcmt').val(id);
      var ajax=$.ajax({
        type:"get",
        url: "{{route('datoscmt')}}",
        data:{id:id}
        });
        ajax.done(function(dato)
        {
          var datos=JSON.parse(dato);
          $('#cmtedit').val(datos.aa[0]);
        });
    });
    $('#btnEditCmt').click(function(event){
        event.preventDefault();
        var token = $("input[name=_token]").val();
        var form = $('#editCmt');
        var route = "{{route('editarcmt')}}";
            $.ajax({
                type: "PUT",
                headers: {"X-CSRF-TOKEN":token},
                url: route,
                data: form.serialize(),
                dataType: "json",
                success: function (data) {
                  listCmt();
                  $('#modalEditarCmt').modal('hide');
                  $('.modal-backdrop').remove();
                }
            });
    });
</script>

resources/views/modal/edit-post.blade.php
<div class="modal fade" id="modalEditarPost" tabindex="-1" role="dialog" aria-labelledby="exampleModalCenterTitle" aria-hidden="true">
  <div class="modal-dialog modal-dialog-centered" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLongTitle">Editar publicacion</h5>
        <button align="right" type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
      </div>
      <div class="modal-body">
        <form id="editPost">
        <input type="hidden" id ="idpost" name="cocos">
          @csrf
          <div>
            <div>
              <input type="text" value="" class="form-control" name="title" id="titledit"  required autocomplete="title" autofocus>
            </div>
          </div>
          <br>
          <div>
            <div>
              <textarea type="text" class="form-control" name="content" id="contentedit"  required autocomplete="content" autofocus></textarea>
            </div>
          </div>
          <div class="modal-footer">
            <button id="btnEdit" type="submit" class="btn btn-primary">Editar</button>
          </div>
        </form>
      </div>
    </div>
  </div>
</div>
<script>
    $('button[id=openmodal]').on('click',function () {
      var id = $(this).data("id");
      $('#idpost').val(id);
      var ajax=$.ajax({
        type:"get",
        url: "{{route('datospost')}}",
        data:{id:id}
        });
        ajax.done(function(dato)
        {
          var datos=JSON.parse(dato);
          $('#titledit').val(datos.aa[0]);
          $('#contentedit').val(datos.aa[1]);
        });
    });
    $('#btnEdit').click(function(event){
        event.preventDefault();
        var token = $("input[name=_token]").val();
        var form = $('#editPost');
        var route = "{{route('editarpost')}}";
            $.ajax({
                type: "PUT",
                headers: {"X-CSRF-TOKEN":token},
                url: route,
                data: form.serialize(),
                dataType: "json",
                success: function (data) {
                  listPost();
                  $('#modalEditarPost').modal('hide');
                  $('.modal-backdrop').remove();
                }
            });
    });
</script>